apiVersion: v1
entries:
  madden-records:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-03-18T02:39:16.305373986Z"
    description: Madden Records – track head-to-head Madden game history
    digest: f5076a6f7ad92ff5ddad070b359c269ed0f9cd0228df162b0e9ea940aeceb6b2
    home: https://github.com/frobobbo/madden-records
    keywords:
    - madden
    - football
    - gaming
    maintainers:
    - name: frobobbo
      url: https://github.com/frobobbo
    name: madden-records
    sources:
    - https://github.com/frobobbo/madden-records
    type: application
    urls:
    - https://frobobbo.github.io/madden-records/charts/madden-records-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-03-18T02:39:16.304966885Z"
    description: Madden Records – track head-to-head Madden game history
    digest: b3500df8ba2fcb1990c31616c04d49172bb3033400bd2b3988bbe39e56918afb
    home: https://github.com/frobobbo/madden-records
    keywords:
    - madden
    - football
    - gaming
    maintainers:
    - name: frobobbo
      url: https://github.com/frobobbo
    name: madden-records
    sources:
    - https://github.com/frobobbo/madden-records
    type: application
    urls:
    - https://frobobbo.github.io/madden-records/charts/madden-records-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-03-18T02:39:16.304419352Z"
    description: Madden Records – track head-to-head Madden game history
    digest: 55e15a8f940e359f66ff80beb1b591a57c9f3d2a00318785d6508369d2cab4fd
    home: https://github.com/frobobbo/madden-records
    keywords:
    - madden
    - football
    - gaming
    maintainers:
    - name: frobobbo
      url: https://github.com/frobobbo
    name: madden-records
    sources:
    - https://github.com/frobobbo/madden-records
    type: application
    urls:
    - https://frobobbo.github.io/madden-records/charts/madden-records-0.1.1.tgz
    version: 0.1.1
generated: "2026-03-18T02:39:16.303835941Z"
