apiVersion: v1
kind: Secret
metadata:
  name: {{ include "madden-records.fullname" . }}-db
  labels:
    {{- include "madden-records.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ include "madden-records.dbPassword" . | quote }}
