{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "madden-records.fullname" . }}-postgresql
  labels:
    {{- include "madden-records.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "madden-records.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgresql
  ports:
    - port: 5432
      targetPort: 5432
{{- end }}
