apiVersion: v1
kind: Service
metadata:
  name: {{ include "madden-records.fullname" . }}-backend
  labels:
    {{- include "madden-records.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "madden-records.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 3001
